In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy as stats
import warnings
warnings.filterwarnings('ignore')

sns.set(style="whitegrid", context="notebook")
plt.rcParams['figure.figsize'] = (15,8)

In [12]:
df = pd.read_csv('amazon_sales_data_2025.csv')
df
df_clean = df.copy()

In [13]:
# Standardize Column Names (Production Rule)
df_clean.columns = (
    df_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)
df_clean.columns

Index(['order_id', 'date', 'product', 'category', 'price', 'quantity',
       'total_sales', 'customer_name', 'customer_location', 'payment_method',
       'status'],
      dtype='object')

In [14]:
df.head()
df.tail()
df.info()
df.shape
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Order ID           250 non-null    object
 1   Date               250 non-null    object
 2   Product            250 non-null    object
 3   Category           250 non-null    object
 4   Price              250 non-null    int64
 5   Quantity           250 non-null    int64
 6   Total Sales        250 non-null    int64
 7   Customer Name      250 non-null    object
 8   Customer Location  250 non-null    object
 9   Payment Method     250 non-null    object
 10  Status             250 non-null    object
dtypes: int64(3), object(8)
memory usage: 21.6+ KB

             Price    Quantity  Total Sales
count   250.000000  250.000000   250.000000
mean    343.580000    2.856000   975.380000
std     380.635808    1.429489  1252.112254
min      15.000000    1.000000    15.000000
25%      40.000000    2.000000   100.000000
50%     150.000000    3.000000   400.000000
75%     600.000000    4.000000  1500.000000
max    1200.000000    5.000000  6000.000000

In [15]:
df.dtypes

Order ID             object
Date                 object
Product              object
Category             object
Price                 int64
Quantity              int64
Total Sales           int64
Customer Name        object
Customer Location    object
Payment Method       object
Status               object
dtype: object

In [16]:
# Check percentage of missing data
missing_df = df.isnull().sum().reset_index()
missing_df.columns = ['Column', 'Missing_Values']
missing_df['Missing_percent'] = (missing_df['Missing_Values'] / len(df)) * 100
missing_df.sort_values(by='Missing_percent', ascending=False)

               Column  Missing_Values  Missing_percent
0            Order ID               0              0.0
1                Date               0              0.0
2             Product               0              0.0
3            Category               0              0.0
4               Price               0              0.0
5            Quantity               0              0.0
6         Total Sales               0              0.0
7       Customer Name               0              0.0
8   Customer Location               0              0.0
9      Payment Method               0              0.0
10             Status               0              0.0

In [17]:
df.duplicated().sum()

np.int64(0)

In [18]:
df.describe().T

             count     mean          std   min    25%    50%     75%     max
Price        250.0  343.580   380.635808  15.0   40.0  150.0   600.0  1200.0
Quantity     250.0    2.856     1.429489   1.0    2.0    3.0     4.0     5.0
Total Sales  250.0  975.380  1252.112254  15.0  100.0  400.0  1500.0  6000.0

In [19]:
df.describe(include='object').T

                  count unique          top freq
Order ID            250    250      ORD0001    1
Date                250     60     10-02-25   10
Product             250     10   Smartphone   35
Category            250      5  Electronics  118
Customer Name       250     10   Emma Clark   32
Customer Location   250     10      Houston   32
Payment Method      250      5       PayPal   60
Status              250      3    Completed   88

In [20]:
df_clean.to_csv("amazon_sales_data_cleaned_2025.csv", index=False)