In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('aqi_india.csv')
df

,city,state,latitude,longitude,datetime,month,day_name,is_weekend,season,time_of_day,...,no2_ugm3,so2_ugm3,o3_ugm3,dust_ugm3,aod,us_aqi,aqi_category,pm25_category_india,festival_period,crop_burning_season
0,agartala,tripura,23.8315,91.2868,05-08-2022 00:00,8,friday,False,monsoon,night,...,21.8,2.7,32,0,0.14,289.0,Very Unhealthy,good,False,False
1,agartala,tripura,23.8315,91.2868,05-08-2022 01:00,8,friday,False,monsoon,night,...,18.5,3.0,33,0,0.14,289.0,Very Unhealthy,good,False,False
2,agartala,tripura,23.8315,91.2868,05-08-2022 02:00,8,friday,False,monsoon,night,...,15.1,3.3,34,0,0.15,54.0,Moderate,good,False,False
3,agartala,tripura,23.8315,91.2868,05-08-2022 03:00,8,friday,False,monsoon,night,...,14.1,3.3,32,0,0.15,54.0,Moderate,good,False,False
4,agartala,tripura,23.8315,91.2868,05-08-2022 04:00,8,friday,False,monsoon,night,...,13.9,3.2,30,0,0.14,54.0,Moderate,good,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
842155,visakhapatnam,andhra pradesh,17.6868,83.2185,26-11-2025 19:00,11,wednesday,False,post_monsoon,evening,...,18.1,38.5,155,4,1.02,172.0,Unhealthy,moderate,False,True
842156,visakhapatnam,andhra pradesh,17.6868,83.2185,26-11-2025 20:00,11,wednesday,False,post_monsoon,evening,...,17.4,34.9,152,4,0.98,172.0,Unhealthy,moderate,False,True
842157,visakhapatnam,andhra pradesh,17.6868,83.2185,26-11-2025 21:00,11,wednesday,False,post_monsoon,night_late,...,17.2,30.9,146,4,0.96,171.0,Unhealthy,moderate,False,True
842158,visakhapatnam,andhra pradesh,17.6868,83.2185,26-11-2025 22:00,11,wednesday,False,post_monsoon,night_late,...,17.1,26.7,138,3,0.94,170.0,Unhealthy,moderate,False,True
842159,visakhapatnam,andhra pradesh,17.6868,83.2185,26-11-2025 23:00,11,wednesday,False,post_monsoon,night_late,...,17.5,23.2,130,3,0.97,170.0,Unhealthy,moderate,False,True

In [5]:
df.head()
df.tail()
df.info()
df.shape
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 842160 entries, 0 to 842159
Data columns (total 31 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   city                 842160 non-null  object
 1   state                842160 non-null  object
 2   latitude             842160 non-null  float64
 3   longitude            842160 non-null  float64
 4   datetime             842160 non-null  object
 5   month                842160 non-null  int64
 6   day_name             842160 non-null  object
 7   is_weekend           842160 non-null  bool
 8   season               842160 non-null  object
 9   time_of_day          842160 non-null  object
 10  humidity_percent     842160 non-null  int64
 11  dew_point_c          842160 non-null  float64
 12  wind_gusts_kmh       842160 non-null  float64
 13  precipitation_mm     842160 non-null  float64
 14  is_raining           842160 non-null  bool
 15  heavy_rain           842160 non-null  bool
 16  pressure_msl_hpa     842160 non-null  float64
 17  cloud_cover_percent  842160 non-null  int64
 18  pm2_5_ugm3           842160 non-null  float64
 19  pm10_ugm3            842160 non-null  float64
 20  co_ugm3              842160 non-null  int64
 21  no2_ugm3             842160 non-null  float64
 22  so2_ugm3             842160 non-null  float64
 23  o3_ugm3              842160 non-null  int64
 24  dust_ugm3            842160 non-null  int64
 25  aod                  842160 non-null  float64
 26  us_aqi               842160 non-null  float64
 27  aqi_category         842160 non-null  object
 28  pm25_category_india  842158 non-null  object
 29  festival_period      842160 non-null  bool
 30  crop_burning_season  842160 non-null  bool
dtypes: bool(5), float64(12), int64(6), object(8)
memory usage: 145.4+ MB

,latitude,longitude,month,humidity_percent,dew_point_c,wind_gusts_kmh,precipitation_mm,pressure_msl_hpa,cloud_cover_percent,pm2_5_ugm3,pm10_ugm3,co_ugm3,no2_ugm3,so2_ugm3,o3_ugm3,dust_ugm3,aod,us_aqi
count,842160.000000,842160.000000,842160.000000,842160.000000,842160.000000,842160.000000,842160.000000,842160.000000,842160.00000,842160.000000,842160.000000,842160.000000,842160.000000,842160.000000,842160.000000,842160.000000,842160.000000,842160.000000
mean,23.129041,82.769207,6.801653,71.324796,17.160777,19.270394,0.197799,1009.489776,50.50123,34.549825,54.014723,444.932728,15.991785,13.390032,80.188893,19.856400,0.463936,94.712182
std,5.543478,6.937205,3.411504,21.362100,7.020427,9.921461,0.915802,5.698795,43.41348,29.652013,54.231554,377.007222,19.896299,18.921014,44.762719,72.359802,0.299889,47.234756
min,8.524100,72.571400,1.000000,3.000000,-11.500000,3.200000,0.000000,979.400000,0.00000,1.900000,2.300000,96.000000,0.000000,0.200000,0.000000,0.000000,0.050000,19.000000
25%,20.296100,77.173400,4.000000,58.000000,12.100000,11.500000,0.000000,1005.400000,2.00000,14.700000,21.500000,235.000000,3.700000,2.800000,47.000000,0.000000,0.240000,59.000000
50%,23.831500,80.946200,7.000000,76.000000,18.600000,17.300000,0.000000,1009.900000,47.00000,25.900000,39.000000,333.000000,9.000000,6.900000,73.000000,2.000000,0.400000,84.000000
75%,26.912400,88.606500,10.000000,89.000000,23.300000,25.200000,0.000000,1013.800000,100.00000,44.200000,66.400000,508.000000,19.900000,15.800000,108.000000,11.000000,0.610000,128.000000
max,31.104800,94.108600,12.000000,100.000000,27.300000,55.100000,51.700000,1028.100000,100.00000,183.500000,420.000000,2903.000000,122.100000,134.200000,228.000000,714.000000,1.700000,289.000000

In [6]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
latitude,842160.0,23.129041,5.543478,8.5241,20.2961,23.8315,26.9124,31.1048
longitude,842160.0,82.769207,6.937205,72.5714,77.1734,80.9462,88.6065,94.1086
month,842160.0,6.801653,3.411504,1.0000,4.0000,7.0000,10.0000,12.0000
humidity_percent,842160.0,71.324796,21.362100,3.0000,58.0000,76.0000,89.0000,100.0000
dew_point_c,842160.0,17.160777,7.020427,-11.5000,12.1000,18.6000,23.3000,27.3000
wind_gusts_kmh,842160.0,19.270394,9.921461,3.2000,11.5000,17.3000,25.2000,55.1000
precipitation_mm,842160.0,0.197799,0.915802,0.0000,0.0000,0.0000,0.0000,51.7000
pressure_msl_hpa,842160.0,1009.489776,5.698795,979.4000,1005.4000,1009.9000,1013.8000,1028.1000
cloud_cover_percent,842160.0,50.501230,43.413480,0.0000,2.0000,47.0000,100.0000,100.0000
pm2_5_ugm3,842160.0,34.549825,29.652013,1.9000,14.7000,25.9000,44.2000,183.5000
pm10_ugm3,842160.0,54.014723,54.231554,2.3000,21.5000,39.0000,66.4000,420.0000
co_ugm3,842160.0,444.932728,377.007222,96.0000,235.0000,333.0000,508.0000,2903.0000
no2_ugm3,842160.0,15.991785,19.896299,0.0000,3.7000,9.0000,19.9000,122.1000
so2_ugm3,842160.0,13.390032,18.921014,0.2000,2.8000,6.9000,15.8000,134.2000
o3_ugm3,842160.0,80.188893,44.762719,0.0000,47.0000,73.0000,108.0000,228.0000
dust_ugm3,842160.0,19.856400,72.359802,0.0000,0.0000,2.0000,11.0000,714.0000
aod,842160.0,0.463936,0.299889,0.0500,0.2400,0.4000,0.6100,1.7000
us_aqi,842160.0,94.712182,47.234756,19.0000,59.0000,84.0000,128.0000,289.0000

In [8]:
cat_cols = df.select_dtypes(include=['object']).columns.tolist()
num_cols = df.select_dtypes(include=['int64','float64']).columns.tolist()
print("Categorical columns:", cat_cols)
print("Numeric columns:", num_cols)

for col in cat_cols:
    print(f"\nValues count for '{col}':")
    print(df[col].value_counts())

Categorical columns: ['city', 'state', 'datetime', 'day_name', 'season', 'time_of_day', 'aqi_category', 'pm25_category_india']
Numeric columns: ['latitude', 'longitude', 'month', 'humidity_percent', 'dew_point_c', 'wind_gusts_kmh', 'precipitation_mm', 'pressure_msl_hpa', 'cloud_cover_percent', 'pm2_5_ugm3', 'pm10_ugm3', 'co_ugm3', 'no2_ugm3', 'so2_ugm3', 'o3_ugm3', 'dust_ugm3', 'aod', 'us_aqi']

Values count for 'city':
city
agartala              29040
itanagar              29040
thiruvananthapuram    29040
shimla                29040
shillong              29040
ranchi                29040
raipur                29040
patna                 29040
panaji                29040
mumbai                29040
lucknow               29040
kolkata               29040
kohima                29040
jaipur                29040
imphal                29040
ahmedabad             29040
hyderabad             29040
guwahati              29040
gurugram              29040
gangtok               29040
delhi                 29040
dehradun              29040
chennai               29040
chandigarh            29040
bhubaneswar           29040
bhopal                29040
bengaluru             29040
aizawl                29040
visakhapatnam         29040
Name: count, dtype: int64

Values count for 'state':
state
tripura              29040
arunachal pradesh    29040
kerala               29040
himachal pradesh     29040
meghalaya            29040
jharkhand            29040
chhattisgarh         29040
bihar                29040
goa                  29040
maharashtra          29040
uttar pradesh        29040
west bengal          29040
nagaland             29040
rajasthan            29040
manipur              29040
gujarat              29040
telangana            29040
assam                29040
haryana              29040
sikkim               29040
delhi                29040
uttarakhand          29040
tamil nadu           29040
punjab               29040
odisha               29040
madhya pradesh       29040
karnataka            29040
mizoram              29040
andhra pradesh       29040
Name: count, dtype: int64

Values count for 'datetime':
datetime
05-08-2022 00:00    29
18-10-2024 22:00    29
20-10-2024 00:00    29
19-10-2024 23:00    29
19-10-2024 22:00    29
                    ..
12-09-2023 03:00    29
12-09-2023 02:00    29
12-09-2023 01:00    29
12-09-2023 00:00    29
26-11-2025 23:00    29
Name: count, Length: 29040, dtype: int64

Values count for 'day_name':
day_name
friday       120408
saturday     120408
sunday       120408
monday       120408
tuesday      120408
wednesday    120408
thursday     119712
Name: count, dtype: int64

Values count for 'season':
season
monsoon         294408
summer          192096
winter          188616
post_monsoon    167040
Name: count, dtype: int64

Values count for 'time_of_day':
time_of_day
night            210540
afternoon        175450
morning          140360
early_morning    105270
evening          105270
night_late       105270
Name: count, dtype: int64

Values count for 'aqi_category':
aqi_category
Moderate                          385833
Unhealthy for Sensitive Groups    175125
Good                              136476
Unhealthy                         130360
Very Unhealthy                     14366
Name: count, dtype: int64

Values count for 'pm25_category_india':
pm25_category_india
good            482562
satisfactory    239169
moderate         73577
poor             26414
very_poor        19698
severe             738
Name: count, dtype: int64

In [9]:
# Check null Values
df.isnull().sum()

city                   0
state                  0
latitude               0
longitude              0
datetime               0
month                  0
day_name               0
is_weekend             0
season                 0
time_of_day            0
humidity_percent       0
dew_point_c            0
wind_gusts_kmh         0
precipitation_mm       0
is_raining             0
heavy_rain             0
pressure_msl_hpa       0
cloud_cover_percent    0
pm2_5_ugm3             0
pm10_ugm3              0
co_ugm3                0
no2_ugm3               0
so2_ugm3               0
o3_ugm3                0
dust_ugm3              0
aod                    0
us_aqi                 0
aqi_category           0
pm25_category_india    2
festival_period        0
crop_burning_season    0
dtype: int64

In [19]:
df['pm25_category_india'] = df['pm25_category_india'].fillna('NA')
df['pm25_category_india'].isnull().sum()
print(df.isnull().sum())
df.to_csv("aqi_india_Cleaned.csv",index=False)

city                   0
state                  0
latitude               0
longitude              0
datetime               0
month                  0
day_name               0
is_weekend             0
season                 0
time_of_day            0
humidity_percent       0
dew_point_c            0
wind_gusts_kmh         0
precipitation_mm       0
is_raining             0
heavy_rain             0
pressure_msl_hpa       0
cloud_cover_percent    0
pm2_5_ugm3             0
pm10_ugm3              0
co_ugm3                0
no2_ugm3               0
so2_ugm3               0
o3_ugm3                0
dust_ugm3              0
aod                    0
us_aqi                 0
aqi_category           0
pm25_category_india    0
festival_period        0
crop_burning_season    0
dtype: int64

In [17]:
# Check duplicate values
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [18]:
# Basic sanity
# city, latitude, longitude
print("City from:", df['city'].min(), "to", df['city'].max())
print("Latitude Range:", df['latitude'].min(), "to", df['latitude'].max())
print("Longitude Range:", df['longitude'].min(), "to", df['longitude'].max())

City from: agartala to visakhapatnam
Latitude Range: 8.5241 to 31.1048
Longitude Range: 72.5714 to 94.1086