In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('dataset.csv')
df

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC_DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL_CONSUMING,COUGHING,SHORTNESS_OF_BREATH,SWALLOWING_DIFFICULTY,CHEST_PAIN,LUNG_CANCER
0,M,65,1,1,1,2,2,1,2,2,2,2,2,2,1,NO
1,F,55,1,2,2,1,1,2,2,2,1,1,1,2,2,NO
2,F,78,2,2,1,1,1,2,1,2,1,1,2,1,1,YES
3,M,60,2,1,1,1,2,1,2,1,1,2,1,2,2,YES
4,F,80,1,1,2,1,1,2,1,2,1,1,1,1,2,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,F,71,2,1,1,2,2,1,1,1,1,2,1,1,2,NO
2996,F,75,1,2,1,1,1,2,2,2,2,1,1,2,1,NO
2997,F,62,2,2,2,1,2,2,2,2,1,1,2,2,2,YES
2998,M,30,1,1,2,2,2,2,2,2,2,1,2,1,2,YES
2999,M,40,1,2,2,1,1,1,2,2,2,1,1,1,1,YES

In [2]:
df.head()
df.tail()
df.info()
df.shape
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   GENDER                 3000 non-null   object
 1   AGE                    3000 non-null   int64
 2   SMOKING                3000 non-null   int64
 3   YELLOW_FINGERS         3000 non-null   int64
 4   ANXIETY                3000 non-null   int64
 5   PEER_PRESSURE          3000 non-null   int64
 6   CHRONIC_DISEASE        3000 non-null   int64
 7   FATIGUE                3000 non-null   int64
 8   ALLERGY                3000 non-null   int64
 9   WHEEZING               3000 non-null   int64
 10  ALCOHOL_CONSUMING      3000 non-null   int64
 11  COUGHING               3000 non-null   int64
 12  SHORTNESS_OF_BREATH    3000 non-null   int64
 13  SWALLOWING_DIFFICULTY  3000 non-null   int64
 14  CHEST_PAIN             3000 non-null   int64
 15  LUNG_CANCER            3000 non-null   object
dtypes: int64(14), object(2)
memory usage: 351.6+ KB

,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC_DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL_CONSUMING,COUGHING,SHORTNESS_OF_BREATH,SWALLOWING_DIFFICULTY,CHEST_PAIN
count,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000
mean,55.169000,1.491000,1.514000,1.494000,1.499000,1.509667,1.489667,1.506667,1.497333,1.491333,1.510667,1.488000,1.489667,1.498667
std,14.723746,0.500002,0.499887,0.500047,0.500082,0.499990,0.499977,0.500039,0.500076,0.500008,0.499970,0.499939,0.499977,0.500082
min,30.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,42.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
50%,55.000000,1.000000,2.000000,1.000000,1.000000,2.000000,1.000000,2.000000,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000
75%,68.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000
max,80.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000

In [4]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
AGE,3000.0,55.169000,14.723746,30.0,42.0,55.0,68.0,80.0
SMOKING,3000.0,1.491000,0.500002,1.0,1.0,1.0,2.0,2.0
YELLOW_FINGERS,3000.0,1.514000,0.499887,1.0,1.0,2.0,2.0,2.0
ANXIETY,3000.0,1.494000,0.500047,1.0,1.0,1.0,2.0,2.0
PEER_PRESSURE,3000.0,1.499000,0.500082,1.0,1.0,1.0,2.0,2.0
CHRONIC_DISEASE,3000.0,1.509667,0.499990,1.0,1.0,2.0,2.0,2.0
FATIGUE,3000.0,1.489667,0.499977,1.0,1.0,1.0,2.0,2.0
ALLERGY,3000.0,1.506667,0.500039,1.0,1.0,2.0,2.0,2.0
WHEEZING,3000.0,1.497333,0.500076,1.0,1.0,1.0,2.0,2.0
ALCOHOL_CONSUMING,3000.0,1.491333,0.500008,1.0,1.0,1.0,2.0,2.0
COUGHING,3000.0,1.510667,0.499970,1.0,1.0,2.0,2.0,2.0
SHORTNESS_OF_BREATH,3000.0,1.488000,0.499939,1.0,1.0,1.0,2.0,2.0
SWALLOWING_DIFFICULTY,3000.0,1.489667,0.499977,1.0,1.0,1.0,2.0,2.0
CHEST_PAIN,3000.0,1.498667,0.500082,1.0,1.0,1.0,2.0,2.0

In [6]:
cat_cols = df.select_dtypes(include = ['object']).columns.tolist()
num_cols = df.select_dtypes(include = ['int64','float64']).columns.tolist()

print("Categorical Columns:", cat_cols)
print("Numerical Columns:", num_cols)

for col in cat_cols:
    print (f"\nValue counts for '{col}':")
    print (df[col].value_counts())
for num in num_cols:
    print(f"\nValue counts for '{num}':")
    print(df[num].value_counts())

Categorical Columns: ['GENDER', 'LUNG_CANCER']
Numerical Columns: ['AGE', 'SMOKING', 'YELLOW_FINGERS', 'ANXIETY', 'PEER_PRESSURE', 'CHRONIC_DISEASE', 'FATIGUE', 'ALLERGY', 'WHEEZING', 'ALCOHOL_CONSUMING', 'COUGHING', 'SHORTNESS_OF_BREATH', 'SWALLOWING_DIFFICULTY', 'CHEST_PAIN']

Value counts for 'GENDER':
GENDER
M    1514
F    1486
Name: count, dtype: int64

Value counts for 'LUNG_CANCER':
LUNG_CANCER
YES    1518
NO     1482
Name: count, dtype: int64

Value counts for 'AGE':
AGE
54    73
67    71
75    71
47    70
69    70
78    69
55    69
79    68
53    66
32    66
39    65
37    65
77    64
46    64
63    63
50    63
33    62
70    61
68    61
35    60
48    60
36    60
71    59
76    59
31    59
56    58
62    58
57    58
52    57
80    57
61    57
60    57
34    57
42    56
41    56
49    56
64    56
59    55
51    55
43    55
44    54
38    53
40    51
58    51
74    50
65    49
66    48
45    47
72    46
73    43
30    42
Name: count, dtype: int64

Value counts for 'SMOKING':
SMOKING
1    1527
2    1473
Name: count, dtype: int64

Value counts for 'YELLOW_FINGERS':
YELLOW_FINGERS
2    1542
1    1458
Name: count, dtype: int64

Value counts for 'ANXIETY':
ANXIETY
1    1518
2    1482
Name: count, dtype: int64

Value counts for 'PEER_PRESSURE':
PEER_PRESSURE
1    1503
2    1497
Name: count, dtype: int64

Value counts for 'CHRONIC_DISEASE':
CHRONIC_DISEASE
2    1529
1    1471
Name: count, dtype: int64

Value counts for 'FATIGUE':
FATIGUE
1    1531
2    1469
Name: count, dtype: int64

Value counts for 'ALLERGY':
ALLERGY
2    1520
1    1480
Name: count, dtype: int64

Value counts for 'WHEEZING':
WHEEZING
1    1508
2    1492
Name: count, dtype: int64

Value counts for 'ALCOHOL_CONSUMING':
ALCOHOL_CONSUMING
1    1526
2    1474
Name: count, dtype: int64

Value counts for 'COUGHING':
COUGHING
2    1532
1    1468
Name: count, dtype: int64

Value counts for 'SHORTNESS_OF_BREATH':
SHORTNESS_OF_BREATH
1    1536
2    1464
Name: count, dtype: int64

Value counts for 'SWALLOWING_DIFFICULTY':
SWALLOWING_DIFFICULTY
1    1531
2    1469
Name: count, dtype: int64

Value counts for 'CHEST_PAIN':
CHEST_PAIN
1    1504
2    1496
Name: count, dtype: int64

In [14]:
# Check Null values
df.isnull().sum()

GENDER                   0
AGE                      0
SMOKING                  0
YELLOW_FINGERS           0
ANXIETY                  0
PEER_PRESSURE            0
CHRONIC_DISEASE          0
FATIGUE                  0
ALLERGY                  0
WHEEZING                 0
ALCOHOL_CONSUMING        0
COUGHING                 0
SHORTNESS_OF_BREATH      0
SWALLOWING_DIFFICULTY    0
CHEST_PAIN               0
LUNG_CANCER              0
dtype: int64

In [10]:
# Check duplicate rows
print("Number of duplicate rows:", df.duplicated().sum())

Number of duplicate rows: 2

In [11]:
# Drop dulicate rows
df = df.drop_duplicates().reset_index(drop=True)
print("Shape after dropping duplicates:",df.shape)

Shape after dropping duplicates: (2998, 16)

In [12]:
print("Number of duplicate rows:", df.duplicated().sum())

Number of duplicate rows: 0

In [13]:
# Basic sanity
# Age, Smoking, Yellow_fingers
print("Age range:", df['AGE'].min(), "to", df['AGE'].max())
print("Smoking count:", df['SMOKING'].min(), "to", df['SMOKING'].max())
print("Yellow fingers count:", df['YELLOW_FINGERS'].min(), "to", df['YELLOW_FINGERS'].max())

Age range: 30 to 80
Smoking count: 1 to 2
Yellow fingers count: 1 to 2