In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('FMCG_3YRS.csv')
df

,date,year,month,day,weekofyear,weekday,is_weekend,is_holiday,temperature,rain_mm,...,discount_pct,promo_flag,gross_sales,net_sales,stock_on_hand,stock_out_flag,lead_time_days,supplier_id,purchase_cost,margin_pct
0,2021-01-01,2021,1,1,53,4,0,1,8.44,1.24,...,0.1,1,167.84,151.06,248,0,11,S008,7.53,0.182
1,2021-01-02,2021,1,2,53,5,1,0,12.61,1.12,...,0.0,0,125.88,125.88,238,0,6,S057,5.19,0.505
2,2021-01-03,2021,1,3,53,6,1,0,12.02,2.69,...,0.3,1,398.62,279.03,238,0,6,S017,5.59,0.168
3,2021-01-04,2021,1,4,1,0,0,0,7.76,4.65,...,0.0,0,83.92,83.92,216,0,7,S012,7.81,0.255
4,2021-01-05,2021,1,5,1,1,0,0,11.16,1.77,...,0.2,1,178.33,142.66,372,0,8,S038,7.62,0.073
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1099995,2022-09-08,2022,9,8,36,3,0,0,12.36,0.05,...,0.0,0,29.94,29.94,233,0,1,S023,3.07,0.384
1099996,2022-09-09,2022,9,9,36,4,0,0,12.51,5.96,...,0.0,0,34.93,34.93,219,0,7,S028,2.53,0.493
1099997,2022-09-10,2022,9,10,36,5,1,0,12.98,6.26,...,0.0,0,44.91,44.91,305,0,10,S027,2.46,0.507
1099998,2022-09-11,2022,9,11,36,6,1,0,16.72,0.20,...,0.0,0,24.95,24.95,282,0,9,S058,2.92,0.414
1099999,2022-09-12,2022,9,12,37,0,0,0,13.41,3.60,...,0.0,0,29.94,29.94,206,0,3,S051,2.87,0.425

In [2]:
df.head()
df.tail()
df.info()
df.shape
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1100000 entries, 0 to 1099999
Data columns (total 33 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   date            1100000 non-null  object
 1   year            1100000 non-null  int64
 2   month           1100000 non-null  int64
 3   day             1100000 non-null  int64
 4   weekofyear      1100000 non-null  int64
 5   weekday         1100000 non-null  int64
 6   is_weekend      1100000 non-null  int64
 7   is_holiday      1100000 non-null  int64
 8   temperature     1100000 non-null  float64
 9   rain_mm         1100000 non-null  float64
 10  store_id        1100000 non-null  object
 11  country         1100000 non-null  object
 12  city            1100000 non-null  object
 13  channel         1100000 non-null  object
 14  latitude        1100000 non-null  float64
 15  longitude       1100000 non-null  float64
 16  sku_id          1100000 non-null  object
 17  sku_name        1100000 non-null  object
 18  category        1100000 non-null  object
 19  subcategory     1100000 non-null  object
 20  brand           1100000 non-null  object
 21  units_sold      1100000 non-null  int64
 22  list_price      1100000 non-null  float64
 23  discount_pct    1100000 non-null  float64
 24  promo_flag      1100000 non-null  int64
 25  gross_sales     1100000 non-null  float64
 26  net_sales       1100000 non-null  float64
 27  stock_on_hand   1100000 non-null  int64
 28  stock_out_flag  1100000 non-null  int64
 29  lead_time_days  1100000 non-null  int64
 30  supplier_id     1100000 non-null  object
 31  purchase_cost   1100000 non-null  float64
 32  margin_pct      1100000 non-null  float64
dtypes: float64(10), int64(12), object(11)
memory usage: 276.9+ MB

,year,month,day,weekofyear,weekday,is_weekend,is_holiday,temperature,rain_mm,latitude,...,list_price,discount_pct,promo_flag,gross_sales,net_sales,stock_on_hand,stock_out_flag,lead_time_days,purchase_cost,margin_pct
count,1.100000e+06,1.100000e+06,1.100000e+06,1.100000e+06,1.100000e+06,1.100000e+06,1.100000e+06,1.100000e+06,1.100000e+06,1.100000e+06,...,1.100000e+06,1.100000e+06,1.100000e+06,1.100000e+06,1.100000e+06,1.100000e+06,1.100000e+06,1.100000e+06,1.100000e+06,1.100000e+06
mean,2.022000e+03,6.525613e+00,1.572044e+01,2.657081e+01,3.005479e+00,2.867582e-01,1.369818e-02,1.281501e+01,2.904106e+00,4.630581e+01,...,7.712100e+00,1.496241e-02,8.023364e-02,4.406806e+02,4.299513e+02,2.994757e+02,3.010364e-02,6.500404e+00,4.625546e+00,3.852405e-01
std,8.164700e-01,3.447760e+00,8.796262e+00,1.505126e+01,2.000451e+00,4.522478e-01,1.162349e-01,3.371587e+00,2.098997e+00,4.602927e+00,...,4.253023e+00,5.477955e-02,2.716547e-01,4.418005e+02,4.224992e+02,8.007292e+01,1.708726e-01,2.014065e+00,2.662604e+00,1.024581e-01
min,2.021000e+03,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.800000e+00,0.000000e+00,4.041706e+01,...,1.080000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,4.900000e-01,-5.000000e-02
25%,2.021000e+03,4.000000e+00,8.000000e+00,1.400000e+01,1.000000e+00,0.000000e+00,0.000000e+00,1.061000e+01,1.220000e+00,4.190833e+01,...,4.200000e+00,0.000000e+00,0.000000e+00,1.324400e+02,1.307675e+02,2.450000e+02,0.000000e+00,5.000000e+00,2.400000e+00,3.120000e-01
50%,2.022000e+03,7.000000e+00,1.600000e+01,2.700000e+01,3.000000e+00,0.000000e+00,0.000000e+00,1.284000e+01,2.570000e+00,4.546266e+01,...,7.380000e+00,0.000000e+00,0.000000e+00,2.828800e+02,2.778600e+02,3.000000e+02,0.000000e+00,6.000000e+00,4.350000e+00,3.890000e-01
75%,2.023000e+03,1.000000e+01,2.300000e+01,4.000000e+01,5.000000e+00,1.000000e+00,0.000000e+00,1.500000e+01,4.150000e+00,5.225287e+01,...,1.165000e+01,0.000000e+00,0.000000e+00,6.052800e+02,5.934600e+02,3.540000e+02,0.000000e+00,8.000000e+00,6.770000e+00,4.690000e-01
max,2.023000e+03,1.200000e+01,3.100000e+01,5.300000e+01,6.000000e+00,1.000000e+00,1.000000e+00,2.283000e+01,1.158000e+01,5.252586e+01,...,1.480000e+01,3.000000e-01,1.000000e+00,6.593900e+03,5.144940e+03,6.980000e+02,1.000000e+00,1.700000e+01,1.110000e+01,5.500000e-01

In [3]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
year,1100000.0,2021.999668,0.816470,2021.00000,2021.00000,2022.00000,2023.00000,2023.00000
month,1100000.0,6.525613,3.447760,1.00000,4.00000,7.00000,10.00000,12.00000
day,1100000.0,15.720444,8.796262,1.00000,8.00000,16.00000,23.00000,31.00000
weekofyear,1100000.0,26.570811,15.051255,1.00000,14.00000,27.00000,40.00000,53.00000
weekday,1100000.0,3.005479,2.000451,0.00000,1.00000,3.00000,5.00000,6.00000
is_weekend,1100000.0,0.286758,0.452248,0.00000,0.00000,0.00000,1.00000,1.00000
is_holiday,1100000.0,0.013698,0.116235,0.00000,0.00000,0.00000,0.00000,1.00000
temperature,1100000.0,12.815005,3.371587,1.80000,10.61000,12.84000,15.00000,22.83000
rain_mm,1100000.0,2.904106,2.098997,0.00000,1.22000,2.57000,4.15000,11.58000
latitude,1100000.0,46.305811,4.602927,40.41706,41.90833,45.46266,52.25287,52.52586
longitude,1100000.0,9.030856,6.727444,-3.67473,2.36046,9.20313,13.39071,20.99579
units_sold,1100000.0,59.196347,45.007217,0.00000,25.00000,49.00000,82.00000,704.00000
list_price,1100000.0,7.712100,4.253023,1.08000,4.20000,7.38000,11.65000,14.80000
discount_pct,1100000.0,0.014962,0.054780,0.00000,0.00000,0.00000,0.00000,0.30000
promo_flag,1100000.0,0.080234,0.271655,0.00000,0.00000,0.00000,0.00000,1.00000
gross_sales,1100000.0,440.680613,441.800507,0.00000,132.44000,282.88000,605.28000,6593.90000
net_sales,1100000.0,429.951321,422.499200,0.00000,130.76750,277.86000,593.46000,5144.94000
stock_on_hand,1100000.0,299.475665,80.072923,0.00000,245.00000,300.00000,354.00000,698.00000
stock_out_flag,1100000.0,0.030104,0.170873,0.00000,0.00000,0.00000,0.00000,1.00000
lead_time_days,1100000.0,6.500404,2.014065,1.00000,5.00000,6.00000,8.00000,17.00000
purchase_cost,1100000.0,4.625546,2.662604,0.49000,2.40000,4.35000,6.77000,11.10000
margin_pct,1100000.0,0.385240,0.102458,-0.05000,0.31200,0.38900,0.46900,0.55000

In [4]:
cat_cols = df.select_dtypes(include=['object']).columns.tolist()
num_cols = df.select_dtypes(include=['int64', 'float64']).columns.tolist()

print("Categorical Columns:", cat_cols)
print("Numerical Columns:", num_cols)

for col in cat_cols:
  print("\nValues for Counts '{col}':")
  print(df[col].value_counts())

Categorical Columns: ['date', 'store_id', 'country', 'city', 'channel', 'sku_id', 'sku_name', 'category', 'subcategory', 'brand', 'supplier_id']
Numerical Columns: ['year', 'month', 'day', 'weekofyear', 'weekday', 'is_weekend', 'is_holiday', 'temperature', 'rain_mm', 'latitude', 'longitude', 'units_sold', 'list_price', 'discount_pct', 'promo_flag', 'gross_sales', 'net_sales', 'stock_on_hand', 'stock_out_flag', 'lead_time_days', 'purchase_cost', 'margin_pct']

Values for Counts '{col}':
date
2022-09-12    1005
2022-09-11    1005
2022-09-10    1005
2022-09-09    1005
2022-09-08    1005
              ...
2023-12-24    1004
2023-12-23    1004
2023-12-22    1004
2023-12-21    1004
2023-12-20    1004
Name: count, Length: 1095, dtype: int64

Values for Counts '{col}':
store_id
STORE0001    87600
STORE0002    87600
STORE0003    87600
STORE0004    87600
STORE0005    87600
STORE0006    87600
STORE0007    87600
STORE0008    87600
STORE0009    87600
STORE0010    87600
STORE0011    87600
STORE0012    87600
STORE0013    48800
Name: count, dtype: int64

Values for Counts '{col}':
country
Italy          350400
Spain          262800
Germany        175200
Poland          87600
France          87600
Austria         87600
Netherlands     48800
Name: count, dtype: int64

Values for Counts '{col}':
city
Berlin       175200
Rome         175200
Milan        175200
Barcelona    175200
Warsaw        87600
Paris         87600
Vienna        87600
Madrid        87600
Amsterdam     48800
Name: count, dtype: int64

Values for Counts '{col}':
channel
Hypermarket    525600
Supermarket    262800
E-commerce     262800
Convenience     48800
Name: count, dtype: int64

Values for Counts '{col}':
sku_id
SKU0020    14235
SKU0001    14235
SKU0096    14235
SKU0039    14235
SKU0015    13140
           ...
SKU0069     7665
SKU0091     7665
SKU0021     7665
SKU0042     6570
SKU0079     6570
Name: count, Length: 102, dtype: int64

Values for Counts '{col}':
sku_name
BrandB Energy drink    14235
BrandA Soda            14235
BrandF Soap            14235
BrandC Biscuits        14235
BrandC Water           13140
                       ...
BrandC Detergent        7665
BrandA Soap             7665
BrandC Energy drink     7665
BrandF Biscuits         6570
BrandA Cleaner          6570
Name: count, Length: 102, dtype: int64

Values for Counts '{col}':
category
Beverages        266085
Snacks           261705
Personal Care    199290
Dairy            196005
Home Care        176915
Name: count, dtype: int64

Values for Counts '{col}':
subcategory
Soda            71175
Shampoo         70080
Toothpaste      70080
Cheese          68985
Milk            67890
Biscuits        67890
Chips           66795
Water           66795
Juice           65700
Chocolate       64605
Softener        63035
Nuts            62415
Energy drink    62415
Soap            59130
Detergent       59130
Yogurt          59130
Cleaner         54750
Name: count, dtype: int64

Values for Counts '{col}':
brand
BrandF    187245
BrandB    186150
BrandD    186150
BrandA    182390
BrandC    180675
BrandE    177390
Name: count, dtype: int64

Values for Counts '{col}':
supplier_id
S037    18579
S051    18572
S041    18533
S040    18529
S020    18507
S019    18502
S007    18481
S060    18474
S028    18469
S024    18469
S044    18465
S045    18464
S042    18451
S004    18448
S012    18438
S034    18438
S005    18437
S001    18437
S017    18430
S057    18423
S008    18408
S039    18403
S006    18396
S023    18394
S059    18394
S055    18380
S010    18354
S009    18345
S056    18344
S043    18339
S029    18315
S048    18315
S026    18314
S025    18300
S033    18299
S018    18287
S047    18287
S015    18280
S053    18277
S032    18277
S031    18272
S003    18266
S022    18240
S036    18239
S030    18227
S050    18222
S013    18222
S027    18214
S011    18212
S014    18206
S054    18198
S038    18190
S002    18183
S021    18175
S052    18164
S016    18152
S046    18143
S035    18116
S049    18097
S058    18008
Name: count, dtype: int64

In [5]:
df.isnull().sum()

date              0
year              0
month             0
day               0
weekofyear        0
weekday           0
is_weekend        0
is_holiday        0
temperature       0
rain_mm           0
store_id          0
country           0
city              0
channel           0
latitude          0
longitude         0
sku_id            0
sku_name          0
category          0
subcategory       0
brand             0
units_sold        0
list_price        0
discount_pct      0
promo_flag        0
gross_sales       0
net_sales         0
stock_on_hand     0
stock_out_flag    0
lead_time_days    0
supplier_id       0
purchase_cost     0
margin_pct        0
dtype: int64