In [2]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("freelancer_vs_skillstack.csv")
df

,freelancer_id,category,primary_skills,years_experience,experience_level,region,country,education,hourly_rate_usd,annual_income_usd,primary_platform
0,FL0001,AI/ML Engineering,"Computer Vision, TensorFlow, Data Science",1.6,junior,Middle East,Israel,Master,66.41,"$58,873.61",Direct Client
1,FL0002,Backend Development,"PHP, Ruby, Go",8.3,senior,Middle East,UAE,Bootcamp,112.79,"$108,183.05",Freelancer
2,FL0003,UI/UX Design,"Sketch, Wireframing, Adobe XD",3.6,mid,North America,US,Self-taught,94.21,"$88,681.22",Freelancer
3,FL0004,DevOps,"Kubernetes, Terraform, AWS",2.3,mid,North America,US,Self-taught,118.87,"$109,229.42",Upwork
4,FL0005,DevOps,"Azure, Docker, Kubernetes",8.8,senior,Latin America,Mexico,Self-taught,82.76,"$66,298.22",LinkedIn
...,...,...,...,...,...,...,...,...,...,...,...
495,FL0496,UI/UX Design,"Adobe XD, Sketch, Figma",9.7,senior,Western Europe,Germany,Self-taught,129.08,"$114,149.16",Direct Client
496,FL0497,Cybersecurity,"Network Security, Security Audit, Cryptography",1.2,junior,Western Europe,Switzerland,Bootcamp,84.37,"$86,158.21",Toptal
497,FL0498,DevOps,"Docker, Kubernetes, Terraform",6.4,senior,North America,US,Bachelor,220.15,"$225,178.75",LinkedIn
498,FL0499,AI/ML Engineering,"Python, NLP, PyTorch",7.4,senior,Western Europe,UK,PhD,220.01,"$236,868.46",Freelancer
499,FL0500,Blockchain,"Ethereum, Solidity, Smart Contracts",10.8,senior,Eastern Europe,Romania,Master,127.68,"$136,126.59",LinkedIn

In [3]:
df.head()
df.tail()
df.info()
df.shape
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   freelancer_id      500 non-null    object
 1   category           500 non-null    object
 2   primary_skills     500 non-null    object
 3   years_experience   500 non-null    float64
 4   experience_level   500 non-null    object
 5   region             500 non-null    object
 6   country            500 non-null    object
 7   education          500 non-null    object
 8   hourly_rate_usd    500 non-null    float64
 9   annual_income_usd  500 non-null    object
 10  primary_platform   500 non-null    object
dtypes: float64(2), object(9)
memory usage: 25.5+ KB

       years_experience  hourly_rate_usd
count        500.000000       500.000000
mean           5.850000        97.149820
std            2.934779        52.697831
min            0.500000        17.280000
25%            3.600000        55.182500
50%            5.600000        84.445000
75%            7.800000       130.497500
max           14.000000       281.470000

In [4]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
years_experience,500.0,5.85000,2.934779,0.50,3.6000,5.600,7.8000,14.00
hourly_rate_usd,500.0,97.14982,52.697831,17.28,55.1825,84.445,130.4975,281.47

In [7]:
cat_cols = df.select_dtypes(include=['object']).columns.tolist()
num_cols = df.select_dtypes(include=['int64', 'float64']).columns.tolist()

print("\ncategorical columns:",cat_cols)
print("\nNumerical Columns:", num_cols)

for col in cat_cols:
    print("\nValues for counts: '{cols}':")
    print(df[col].value_counts())

categorical columns: ['freelancer_id', 'category', 'primary_skills', 'experience_level', 'region', 'country', 'education', 'annual_income_usd', 'primary_platform']

Numerical Columns: ['years_experience', 'hourly_rate_usd']

Values for counts: '{cols}':
freelancer_id
FL0001    1
FL0330    1
FL0343    1
FL0342    1
FL0341    1
         ..
FL0162    1
FL0161    1
FL0160    1
FL0159    1
FL0500    1
Name: count, Length: 500, dtype: int64

Values for counts: '{cols}':
category
Cybersecurity          68
DevOps                 58
Web Development        58
Full Stack             51
UI/UX Design           48
Blockchain             46
AI/ML Engineering      45
Backend Development    45
Data Engineering       45
Mobile Development     36
Name: count, dtype: int64

Values for counts: '{cols}':
primary_skills
Security Audit, Cryptography, Penetration Testing      6
Cryptography, Network Security, Security Audit         6
Network Security, Penetration Testing, Cryptography    6
Network Security, Cryptography, Penetration Testing    5
Cryptography, Penetration Testing, Security Audit      5
                                                      ..
React, JavaScript, HTML/CSS                            1
Node.js, React, JavaScript                             1
Angular, JavaScript, HTML/CSS                          1
Terraform, CI/CD, AWS                                  1
Ethereum, Solidity, Smart Contracts                    1
Name: count, Length: 377, dtype: int64

Values for counts: '{cols}':
experience_level
senior    279
mid       175
junior     46
Name: count, dtype: int64

Values for counts: '{cols}':
region
Eastern Europe    84
Middle East       81
Western Europe    72
Africa            72
Latin America     69
North America     63
Asia Pacific      59
Name: count, dtype: int64

Values for counts: '{cols}':
country
Israel          42
US              39
UAE             39
Nigeria         36
South Africa    36
Ukraine         31
Romania         28
Poland          25
Canada          24
Brazil          24
Switzerland     21
Germany         20
UK              17
Colombia        15
Argentina       15
Mexico          15
Philippines     14
France          14
Australia       14
China           12
India           11
Japan            8
Name: count, dtype: int64

Values for counts: '{cols}':
education
Bachelor       187
Master         139
Self-taught    112
Bootcamp        38
PhD             24
Name: count, dtype: int64

Values for counts: '{cols}':
annual_income_usd
$58,873.61     1
$86,179.93     1
$49,673.89     1
$18,318.80     1
$220,331.62    1
              ..
$61,645.29     1
$246,290.18    1
$66,136.05     1
$134,532.39    1
$136,126.59    1
Name: count, Length: 500, dtype: int64

Values for counts: '{cols}':
primary_platform
Direct Client    143
Upwork           120
Freelancer        71
LinkedIn          59
Toptal            54
Fiverr            43
Other             10
Name: count, dtype: int64

In [8]:
df.isnull().sum()

freelancer_id        0
category             0
primary_skills       0
years_experience     0
experience_level     0
region               0
country              0
education            0
hourly_rate_usd      0
annual_income_usd    0
primary_platform     0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.to_csv("freelancer_cleaned.csv")